1. Write a Python Program to Add Two Matrices?

In [3]:
# By using numpy
import numpy as np

mat1 = np.array([[1,2,3],
                 [4,5,6]])
mat2 = np.array([[1,2,3],
                 [4,5,6]])
mat1+mat2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [20]:
# Without using numpy

def mat_add(mat1, mat2):
    new_mat = list()
    for i in range(len(mat1)):
        new_mat.append(list())
        for j in range(len(mat1[i])):
            new_mat[i].append(mat1[i][j]+mat2[i][j])
    return new_mat

mat1 = np.array([[1,2,3],
                 [4,5,6]])
mat2 = np.array([[1,2,3],
                 [4,5,6]])

mat_add(mat1, mat2)

[[2, 4, 6], [8, 10, 12]]

2. Write a Python Program to Multiply Two Matrices?

In [21]:
# By using numpy
import numpy as np

mat1 = np.array([[1,2,3],
                 [4,5,6]])
mat2 = np.array([[1,2,3],
                 [4,5,6]])
mat1*mat2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [26]:
# Without using numpy

def mat_mul(mat1, mat2):
    new_mat = list()
    for i in range(len(mat1)):
        new_mat.append(list())
        for j in range(len(mat1[i])):
            new_mat[i].append(mat1[i][j]*mat2[i][j])
    return new_mat

mat1 = np.array([[1,2,3],
                 [4,5,6]])
mat2 = np.array([[1,2,3],
                 [4,5,6]])

mat_mul(mat1, mat2)

[[1, 4, 9], [16, 25, 36]]

3. Write a Python Program to Transpose a Matrix?

In [24]:
# By using numpy
import numpy as np

mat1 = np.array([[1,2,3],
                 [4,5,6]])
mat1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [30]:
# Without using numpy

def mat_transpose(mat):
    new_mat = list()
    rows = len(mat)
    cols = len(mat[0])
    for i in range(cols):
        new_mat.append(list())
        for j in range(rows):
            new_mat[i].append(mat[j][i])
    return new_mat

mat1 = np.array([[1,2,3],
                 [4,5,6]])
mat_transpose(mat1)

[[1, 4], [2, 5], [3, 6]]

4. Write a Python Program to Sort Words in Alphabetic Order?

In [32]:
str = "programming in python is cool"

' '.join(sorted(str.split()))

'cool in is programming python'

5. Write a Python Program to Remove Punctuation From a String?

In [46]:
import re

str1 = "Hello world! python programming is cool! #python@program"
re.sub("[^\w\s]", '', str1)

'Hello world python programming is cool pythonprogram'